[theme]
primaryColor = "#7561FF"
backgroundColor = "#F7F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202235"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
